# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delta.Profile'),
        ),
    ]
