# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0002_seat_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='username', max_length=200),
        ),
    ]
