# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delta', '0003_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
